# Generated by Django 2.0.5 on 2018-05-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование предмета')),
                ('description', models.TextField(max_length=200, verbose_name='Описание предмета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за предмет')),
            ],
        ),
    ]
