# Generated by Django 2.0.5 on 2018-05-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='img',
            field=models.CharField(default=None, max_length=15, verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
