# Generated by Django 2.0.5 on 2018-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cloth_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='reduced_from',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Старая цена за предмет'),
            preserve_default=False,
        ),
    ]
