# Generated by Django 2.0.5 on 2018-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cloth_reduced_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='img',
            field=models.CharField(max_length=15, null=True, verbose_name='Картинка'),
        ),
    ]
