# Generated by Django 2.0.5 on 2018-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180528_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='img',
            field=models.ImageField(default=None, upload_to='clothes', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
