# Generated by Django 2.0.5 on 2018-05-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180528_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='img',
            field=models.ImageField(null=True, upload_to='clothes', verbose_name='Картинка'),
        ),
    ]
